"""
GPX Vector Stream Exporter
Serializes calculated canopy routes into standard .gpx files
for Garmin, Apple Watch, Strava, and handheld GPS devices.
"""

from datetime import datetime, timezone
from typing import Dict, Any, List

class GPXExporter:
    @staticmethod
    def export_route_to_gpx(route_data: Dict[str, Any]) -> str:
        """
        Builds a compliant GPX 1.1 XML string from route coordinates.
        """
        route_id = route_data.get("route_id", "arbor_stride")
        activity = route_data.get("activity", "walk").capitalize()
        canopy_pct = route_data.get("avg_canopy_pct", 75)
        temp_savings = route_data.get("temp_savings_f", 8.0)
        coords = route_data.get("coordinates", [])

        now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

        gpx_lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<gpx version="1.1" creator="ArborStride AI - Touch Grass"',
            '     xmlns="http://www.topografix.com/GPX/1/1"',
            '     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
            '     xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">',
            f'  <metadata>',
            f'    <name>ArborStride {activity} - {canopy_pct}% Tree Canopy</name>',
            f'    <desc>Thermal microclimate route saving {temp_savings}°F off asphalt heat. Generated by ArborStride AI with Prior Labs TabPFN and Google Gemma.</desc>',
            f'    <time>{now_iso}</time>',
            f'  </metadata>',
            f'  <trk>',
            f'    <name>ArborStride {activity} Loop</name>',
            f'    <type>{activity}</type>',
            f'    <trkseg>'
        ]

        # Add each coordinate as a trackpoint
        for pt in coords:
            # pt is [lng, lat]
            lng, lat = pt[0], pt[1]
            gpx_lines.append(f'      <trkpt lat="{lat:.6f}" lon="{lng:.6f}">')
            gpx_lines.append(f'        <time>{now_iso}</time>')
            gpx_lines.append(f'      </trkpt>')

        gpx_lines.extend([
            '    </trkseg>',
            '  </trk>',
            '</gpx>'
        ])

        return "\n".join(gpx_lines)
